# To add a new tool, add an entry to this table.
[tools]
rojo = "rojo-rbx/rojo@7.4.1"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.1"
wally = "UpliftGames/wally@0.3.2"
# rojo = "rojo-rbx/rojo@6.2.0"